helm:
  parameters:
    - name: testkube-dashboard.image.repository
      value: kubeshop/testkube-dashboard
      forcestring: true
    - name: testkube-dashboard.image.tag
      value: sha-b8e7065
      forcestring: true
