name: "Docker Action"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  docker-action:
    name: Docker Action
    runs-on: ubuntu-latest
    steps:
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME_DEV }}
          location: ${{ secrets.GKE_ZONE_DEV }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Create test
        id: create_test
        uses: kubeshop/testkube-docker-action@4a81be5e738c88baef80b11e63c6087cd09a0ed0
        with:
          command: create
          resource: test
          namespace: testkube
          parameters: "--type k6/script --name testkube-github-action"
          stdin: "import http from 'k6/http';\nimport { sleep,check } from 'k6';"

