name: Testkube Docker Action.

on:
  push:
    branches:
      - vsukhin/feature/docker-action

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER_NAME_DEV: ${{ secrets.GKE_CLUSTER_NAME_DEV }} # Add your cluster name here.
  GKE_ZONE_DEV: ${{ secrets.GKE_ZONE_DEV }} # Add your cluster zone here.
  DEPLOYMENT_NAME: testkube # Add your deployment name here.
  POSTMAN_TEST_FILE_NANE: TestKube-Sanity.postman_collection.json
  POSTMAN_TEST_FILE_PATH: test/postman

jobs:
  get_dev_test:
    name: get test for DEV GKE.
    runs-on: ubuntu-latest
    steps:
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}


      # Getting test CRD
      - name: Get test CRD
        id: test
        uses: kubeshop/testkube-docker-action@v1
        with:
          command: get
          resource: test 
          parameters: failing-soapui --crd-only

      # Use the output from the `test` step
      - name: Get the output result
        run: echo '${{ steps.test.outputs.result }}'
